# -*- coding: utf-8 -*-
"""agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vWhIdLUfSMZ5lrTLfrn6cZdmQNAqjn8z
"""

!pip install -U langchain_community --quiet

from langchain_community.document_loaders import TextLoader

loader_text = TextLoader("Company_sample.txt")
docs = loader_text.load()
print(docs)

from langchain_text_splitters import RecursiveCharacterTextSplitter
splitter = RecursiveCharacterTextSplitter(chunk_size = 500, chunk_overlap = 50)
chunks = splitter.split_documents(docs)

import os
os.environ["GOOGLE_API_KEY"] = os.getenv("GOOGLE_API_KEY", "")

# Commented out IPython magic to ensure Python compatibility.
# %pip install -U langchain-google-genai --quiet
import os
from langchain_google_genai import GoogleGenerativeAIEmbeddings
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
embeddings = GoogleGenerativeAIEmbeddings(
    model="models/gemini-embedding-001",
    google_api_key=GOOGLE_API_KEY
)

# Commented out IPython magic to ensure Python compatibility.
# %pip install faiss-cpu --quiet
from langchain_community.vectorstores import FAISS
vector_store = FAISS.from_documents(chunks, embeddings)

retriever = vector_store.as_retriever(search_type="similarity", k = 3)

from langchain_core.prompts import PromptTemplate
prompt_template = PromptTemplate(

    input_variables = {"context", "question"},

    template = """You are a helpful assistant that answers questions based on the provided context.

    Context:
    {context}

    Question: {question}

    Answer: Provide a clear and concise answer based on the context above, if the context doesn't contain enough information to answer the answer then say so"""

)

from langchain_google_genai import ChatGoogleGenerativeAI
llm = ChatGoogleGenerativeAI(
    model = "gemini-2.5-flash",
    google_api_key = GOOGLE_API_KEY,
    temperature = 0.5,
    convert_system_message_to_human = True
)
response = llm.invoke("what are the core values of ACME Corporation as given in the txt file?")
print(response.content)

def rag(query):
  docs = retriever.invoke(query)
  context = "\n\n".join([doc.page_content for doc in docs])
  prompt = prompt_template.format(context=context, question=query)
  response = llm.invoke(prompt)
  answer = response.content
  return answer
rag("what are the core values of ACME Corporation as given in the txt file?")